apiVersion: v1
kind: Config
current-context: terraform
clusters:
- name: cluster
  cluster:
    certificate-authority-data: ${aws_eks_cluster_ca_cert}
    server: ${aws_eks_cluster_endpoint}
contexts:
- name: terraform
  context:
    cluster: cluster
    user: terraform
users:
- name: terraform
  user:
    token: ${aws_eks_cluster_token}